spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:postgresql://localhost:5432/parkfinder
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: on
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    open-in-view: off